using System;
using UnityEngine;

namespace DigitalMedia.Misc
{
    public class AfterImageSprite : MonoBehaviour
    {
        [SerializeField] private float activeTime = 0.1f;
        private float timeActivated;
        private float alpha; 
        [SerializeField] private float alphaSet = 0.8f;
        private float alphaMultiplier = 0.85f;

        private Transform player;

        private SpriteRenderer sr;
        private SpriteRenderer playerSR;

        private Color color;

        private void OnEnable()
        {
            sr = GetComponent<SpriteRenderer>();
            player = GameObject.FindGameObjectWithTag("Player").transform;
            playerSR = player.GetComponent<SpriteRenderer>();

            alpha = alphaSet;
            sr.sprite = playerSR.sprite;
            transform.position = player.position;
            transform.rotation = player.rotation;
            timeActivated = Time.time;
        }


        private void Update()
        {
            alpha *= alphaMultiplier;
            color = new Color(1, 1, 1, alpha);
            sr.color = color;

            if (Time.time >= (timeActivated + activeTime))
            {
                PlayerAfterImagePool.Instance.AddToPool(gameObject);
            }
        }
    }
}